name: Check code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install poetry
        poetry install

    - name: Run linting
      run: |
        make linting

    - name: Run mypy check
      run: |
        make mypy

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}        
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}  
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        env:
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}        
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}  
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
          TEST_DIALECT: ${{ secrets.TEST_DIALECT }}
          TEST_DRIVER: ${{ secrets.TEST_DRIVER }} 
          TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }} 
          TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }} 
          TEST_DB_SCHEMA: ${{ secrets.TEST_DB_SCHEMA }} 
        
      - name: Install dependencies
        run: |
          python3 -m pip install poetry
          poetry install

      - name: Run test
        run: |
            make test
    